//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSFacadeService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosMensaje", Namespace="http://schemas.datacontract.org/2004/07/Olimpia.SMS.FacadeService")]
    public partial class DatosMensaje : object
    {
        
        private string CodReferenciaClienteField;
        
        private string CodigoPaisField;
        
        private System.DateTime FechaEnvioField;
        
        private string FormatoField;
        
        private string MensajeField;
        
        private string NumeroDestinoField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodReferenciaCliente
        {
            get
            {
                return this.CodReferenciaClienteField;
            }
            set
            {
                this.CodReferenciaClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPais
        {
            get
            {
                return this.CodigoPaisField;
            }
            set
            {
                this.CodigoPaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEnvio
        {
            get
            {
                return this.FechaEnvioField;
            }
            set
            {
                this.FechaEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formato
        {
            get
            {
                return this.FormatoField;
            }
            set
            {
                this.FormatoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDestino
        {
            get
            {
                return this.NumeroDestinoField;
            }
            set
            {
                this.NumeroDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusMessage", Namespace="http://schemas.datacontract.org/2004/07/SMSFacadeService")]
    public partial class StatusMessage : object
    {
        
        private string ExtensionData1Field;
        
        private string MessageField;
        
        private SMSFacadeService.Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData")]
        public string ExtensionData1
        {
            get
            {
                return this.ExtensionData1Field;
            }
            set
            {
                this.ExtensionData1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SMSFacadeService.Status Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/Olimpia.SMS.Integration.Messaging")]
    public enum Status : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueueTimeOut = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SocketTimeOut = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SocketErrorBeforeSend = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SocketErrorAfterSend = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MensajeDuplicado = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoResponse = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NúmeroNoValido = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSFacadeService.ISMSFacade")]
    public interface ISMSFacade
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISMSFacade/EnviarMensaje", ReplyAction="http://tempuri.org/ISMSFacade/EnviarMensajeResponse")]
        System.Threading.Tasks.Task<SMSFacadeService.StatusMessage> EnviarMensajeAsync(int idTipoMensaje, SMSFacadeService.DatosMensaje mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface ISMSFacadeChannel : SMSFacadeService.ISMSFacade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class SMSFacadeClient : System.ServiceModel.ClientBase<SMSFacadeService.ISMSFacade>, SMSFacadeService.ISMSFacade
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SMSFacadeClient() : 
                base(SMSFacadeClient.GetDefaultBinding(), SMSFacadeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_ISMSFacade.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSFacadeClient(EndpointConfiguration endpointConfiguration) : 
                base(SMSFacadeClient.GetBindingForEndpoint(endpointConfiguration), SMSFacadeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSFacadeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SMSFacadeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSFacadeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SMSFacadeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SMSFacadeService.StatusMessage> EnviarMensajeAsync(int idTipoMensaje, SMSFacadeService.DatosMensaje mensaje)
        {
            return base.Channel.EnviarMensajeAsync(idTipoMensaje, mensaje);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_ISMSFacade))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_ISMSFacade))
            {
                return new System.ServiceModel.EndpointAddress("https://olsrvpruwbce01.olimpiait.local:6252/SMSFacadeServicio.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SMSFacadeClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_ISMSFacade);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SMSFacadeClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_ISMSFacade);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_ISMSFacade,
        }
    }
}
